### ISSUE TITLE
Background color in whitout background color setting.

### ISSUE THREAD

**Issue by extremecoder2020** [maheshkareeya/color#2]
Hello,
I don't know if that behavior is expected. But i guess very strange.
When we set a background color, this background works in other lines without this setting.
The background color change if i setting a new one.
According the documentation, i guess current setting is aplyed only in current console.log
system observation: Windows 10 and vscode with latest update.
![Anotação 2020-06-04 102628](https://user-images.githubusercontent.com/45907874/83762969-8824e280-a64e-11ea-97cc-84ebb345f4d2.png)

Thanks!

**Comment by maheshkareeya** [comment]
use reset in next line
clc.reset.red.bgBlue("Something")

**Comment by itsmaheshkariya** [comment]
Try to use reset

clc.red.bgBlue("I am red with blue background");
clc.red.bgBlack.reset("I am with black one")

**Comment by extremecoder2020** [comment]
Error in console:
```
error: TS2349 [ERROR]: This expression is not callable.
  Type 'Clc' has no call signatures.
console.log(clc.red.bgBlack.reset("I am with black one"));
                            ~~~~~
```
